build system

diff --git a/.github/workflows/release.yml b/.github/workflows/release.yml
--- a/.github/workflows/release.yml
+++ b/.github/workflows/release.yml
@@ -1,28 +1,29 @@
 ---
-name: Application Build
+name: Application Publish (Release)
+
+permissions:
+  contents: write
 
 on:
+  workflow_dispatch:
   push:
-    branches-ignore:
-      - "release/*"
-    tags-ignore:
-      - "*"
-  pull_request:
+    tags:
+      - "v*"
 
 jobs:
   build:
     env:
+      BUILD_NUMBER: ${{ github.run_number }}
       UPDATE_FEED_OWNER: Dexus
       UPDATE_FEED_REPOSITORY: Deepnest
-      BUILD_NUMBER: ${{ github.run_number }}
       PREBUILDS_ONLY: 1
     strategy:
       matrix:
         os:
           [
-            #"ubuntu-24.04",
-            #"ubuntu-24.04-arm",
-            #"windows-latest",
+            "ubuntu-24.04",
+            "ubuntu-24.04-arm",
+            "windows-latest",
             "macos-latest",
             "macos-13",
           ]
@@ -33,10 +34,10 @@ jobs:
             arch: "x64"
           - os: "ubuntu-24.04"
             arch: "arm64"
-          - os: "macos-13"
-            arch: "arm64"
           - os: "macos-latest"
             arch: "x64"
+          - os: "macos-13"
+            arch: "arm64"
           # Exclude MAS target for non-macOS platforms
           - os: "ubuntu-24.04"
             target: "mas"
@@ -45,11 +46,11 @@ jobs:
           - os: "windows-latest"
             target: "mas"
           # Include only one target for each macOS build to avoid duplicates
-          - os: "macos-13"
-            target: ""
-          - os: "macos-latest"
-            target: ""
-      fail-fast: true
+          # - os: "macos-13"
+          #   target: ""
+          # - os: "macos-latest"
+          #   target: ""
+      fail-fast: true # Explicitly failing fast because this is a publish. We want to bail the entire release if something went wrong with another build
 
     runs-on: ${{ matrix.os }}
 
@@ -66,13 +67,12 @@ jobs:
           cache-dependency-path: '**/package-lock.json'
 
       - name: Install dependencies
-        run: |
-          npm install
+        run: npm install
 
       - name: Install distribution dependencies
         shell: bash
         run: |
-          if [[ "${{ matrix.os }}" == "ubuntu-24.04" || "${{ matrix.os }}" = "ubuntu-24.04-arm" ]]; then
+          if [[ ("${{ matrix.os }}" == "ubuntu-24.04" && "${{ matrix.arch }}" == "x64") || ("${{ matrix.os }}" == "ubuntu-24.04-arm" && "${{ matrix.arch }}" == "arm64") ]]; then
             sudo apt-get update && sudo apt-get upgrade && sudo apt-get install -y flatpak flatpak-builder elfutils snapd libgl1 libglx-mesa0;
             flatpak remote-add --if-not-exists --user flathub https://dl.flathub.org/repo/flathub.flatpakrepo ;
             flatpak remote-add --if-not-exists --user flathub https://flathub.org/repo/flathub.flatpakrepo ;
@@ -84,10 +84,7 @@ jobs:
             #sudo snap install snapcraft --classic;
             #sudo snap install core22 --classic;
           fi
-          if [[ "${{ matrix.os }}" == "macos-latest" || "${{ matrix.os }}" == "macos-13" ]]; then
-            brew install python-setuptools;
-          fi
-          # if [ "${{ matrix.os }}" == "windows-latest" ]; then
+          # if [ "${{ matrix.os.name }}" == "windows" ]; then
           #   choco install -y nsis;
           #   choco install wixtoolset  --version=3.14.0;
           # fi
@@ -128,38 +125,71 @@ jobs:
           APPLE_KEYCHAIN_PASS: ${{ secrets.APPLE_KEYCHAIN_PASS }}
           APPLE_NOTARY_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
 
-      - name: Build (${{ matrix.arch }})
+      - name: Publish Dry (${{ matrix.arch }})
         shell: bash
         env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           NOTARIZATION_KEY_PATH: "${{ runner.temp }}/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8"
-          APPLE_NOTARY_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
           APPLE_KEYCHAIN_PATH: "${{ runner.temp }}/${{ secrets.APPLE_KEYCHAIN }}"
+          APPLE_NOTARY_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
           APPLE_DEVELOPER_ID_APPLICATION: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}
           APPLE_DEVELOPER_ID_INSTALLER: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER }}
           APPLE_MAS_IDENTITY: ${{ secrets.APPLE_MAS_IDENTITY }}
           APPLE_MAS_INSTALLER_IDENTITY: ${{ secrets.APPLE_MAS_INSTALLER_IDENTITY }}
           APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
-          APPLE_API_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
           CI: "true"
           BUILD_NUMBER: ${{ github.run_number }}
           MAKER_ARCH: ${{ matrix.arch }}
           MAKER_PLATFORM: ${{ matrix.target == 'mas' && 'mas' || '' }}
         run: |
-          mkdir -p out/make/
-          if [[ "${{ matrix.target }}" == "mas" && ("${{ matrix.os }}" == "macos-13" || "${{ matrix.os }}" == "macos-latest") ]]; then
-            npm run make -- --arch ${{ matrix.arch }} || find ./out -type f
-            npm run make -- --arch universal --platform mas || find ./out -type f
-          else
-            npm run make -- --arch ${{ matrix.arch }}
+          if [[ ("${{ matrix.os }}" == "ubuntu-24.04" && "${{ matrix.arch }}" == "x64") || ("${{ matrix.os }}" == "ubuntu-24.04-arm" && "${{ matrix.arch }}" == "arm64") ]]; then
+            npm run publish:dry -- --arch ${{ matrix.arch }}
           fi
-          find ./out -type f
+          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
+            npm run publish:dry -- --arch ${{ matrix.arch }}
+          fi
+          if [[ ("${{ matrix.os }}" == "macos-13" && "${{ matrix.arch }}" == "x64" && "${{ matrix.target }}" == "") || ("${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "arm64" && "${{ matrix.target }}" == "") ]]; then
+            npm run publish:dry -- --arch ${{ matrix.arch }}
+          fi
+          if [[ ("${{ matrix.os }}" == "macos-13" && "${{ matrix.arch }}" == "x64" && "${{ matrix.target }}" == "mas") || ("${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "arm64" && "${{ matrix.target }}" == "mas") ]]; then
+            npm run publish:dry -- --arch universal --platform mas
+          fi
+
+      - name: Publish From Dry (${{ matrix.arch }})
+        shell: bash
+        env:
+          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          NOTARIZATION_KEY_PATH: "${{ runner.temp }}/AuthKey_${{ secrets.APPLE_API_KEY_ID }}.p8"
+          APPLE_KEYCHAIN_PATH: "${{ runner.temp }}/${{ secrets.APPLE_KEYCHAIN }}"
+          APPLE_NOTARY_KEY_ID: ${{ secrets.APPLE_API_KEY_ID }}
+          APPLE_DEVELOPER_ID_APPLICATION: ${{ secrets.APPLE_DEVELOPER_ID_APPLICATION }}
+          APPLE_DEVELOPER_ID_INSTALLER: ${{ secrets.APPLE_DEVELOPER_ID_INSTALLER }}
+          APPLE_MAS_IDENTITY: ${{ secrets.APPLE_MAS_IDENTITY }}
+          APPLE_MAS_INSTALLER_IDENTITY: ${{ secrets.APPLE_MAS_INSTALLER_IDENTITY }}
+          APPLE_API_ISSUER: ${{ secrets.APPLE_API_ISSUER }}
+          CI: "true"
+          BUILD_NUMBER: ${{ github.run_number }}
+          MAKER_ARCH: ${{ matrix.arch }}
+          MAKER_PLATFORM: ${{ matrix.target == 'mas' && 'mas' || '' }}
+          S3_BUCKET: ${{ secrets.S3_BUCKET }}
+          S3_REGION: ${{ secrets.S3_REGION }}
+          S3_ACCESS_KEY_ID: ${{ secrets.S3_KEY }}
+          S3_SECRET_ACCESS_KEY: ${{ secrets.S3_SECRET }}
+          S3_ENDPOINT: ${{ secrets.S3_HOST }}
+        run: |
+          if [[ ("${{ matrix.os }}" == "ubuntu-24.04" && "${{ matrix.arch }}" == "x64") || ("${{ matrix.os }}" == "ubuntu-24.04-arm" && "${{ matrix.arch }}" == "arm64") ]]; then
+            npm run publish:fromdry -- --arch ${{ matrix.arch }}
+          fi
+          if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
+            npm run publish:fromdry -- --arch ${{ matrix.arch }}
+          fi
+          if [[ ("${{ matrix.os }}" == "macos-13" && "${{ matrix.arch }}" == "x64" && "${{ matrix.target }}" == "") || ("${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "arm64" && "${{ matrix.target }}" == "") ]]; then
+            npm run publish:fromdry -- --arch ${{ matrix.arch }}
+          fi
+          if [[ ("${{ matrix.os }}" == "macos-13" && "${{ matrix.arch }}" == "x64" && "${{ matrix.target }}" == "mas") || ("${{ matrix.os }}" == "macos-latest" && "${{ matrix.arch }}" == "arm64" && "${{ matrix.target }}" == "mas") ]]; then
+            npm run publish:fromdry -- --arch universal --platform mas
+          fi
 
       # TODO: add AppImage for linux if we can get snap and/or flatpak to work
-
-      - name: Upload artifacts (${{ matrix.arch }})
-        uses: actions/upload-artifact@v4
-        #if: ${{ ((matrix.os == 'ubuntu-24.04' && matrix.arch == 'x64') || (matrix.os == 'ubuntu-24.04-arm' && matrix.arch == 'arm64') || (matrix.os == 'windows' && (matrix.arch == 'x64' || matrix.arch == 'arm64')) || (matrix.os == 'macos_x64' && matrix.arch == 'x64') || (matrix.os == 'macos' && matrix.arch == 'arm64')) }}
-        with:
-          name: dist-${{ matrix.os }}-${{ matrix.arch }}
-          path: |
-            out/make/
+      # https://github.com/AppImage/appimagetool?tab=readme-ov-file
+      # something like this: https://github.com/tropy/tropy/blob/bdf729db09e68b9ea514e2e1cbd67faac42c1872/scripts/pack.js#L116
